services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notes_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/notes_app_db
      JWT_SECRET_KEY: your_super_secret_key_here_change_in_production
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      HOST: 0.0.0.0
      PORT: 8001
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  notes-service:
    build: ./notes_service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/notes_app_db
      JWT_SECRET_KEY: your_super_secret_key_here_change_in_production
      JWT_ALGORITHM: HS256
      AUTH_SERVICE_URL: http://auth-service:8001
      HOST: 0.0.0.0
      PORT: 8002
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend_service
    ports:
      - "80:80"
    environment:
      REACT_APP_AUTH_SERVICE_URL: /api/auth
      REACT_APP_NOTES_SERVICE_URL: /api/notes
    depends_on:
      auth-service:
        condition: service_healthy
      notes-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data: