apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: notes-app
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.monitoring.svc.cluster.local:9090
      access: proxy
      isDefault: true
      editable: true
      jsonData:
        httpMethod: GET
        queryTimeout: 60s
        timeInterval: 15s
      uid: prometheus-uid
